export const ActionTypes  ={
    GET_PRODUCTS : "GET_PRODUCTS",
    ADD_TO_CART_PRODUCT:"ADD_TO_CART_PRODUCT",
    CURRENT_CART_LIST:"CURRENT_CART_LIST",
    PREV_CART_LIST:"PREV_CART_LIST",
    REMOVE_ITEM:"REMOVE_ITEM",
}